version: '3'
services:
  pack_delivery_api:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - '.:/go/src/github.com/dhurimkelmendi/pack_delivery_api'
    environment:
      API_ORIGIN: 'http://localhost:8080'
      ENV: development
