version: '3'
services:
  pack_delivery_api-postgres-server:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: pack_delivery_api_db
      POSTGRES_USER: pack_delivery_api
      POSTGRES_PASSWORD: 'pack_delivery_api_password'
  pack_delivery_api:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - '.:/go/src/github.com/dhurimkelmendi/pack_delivery_api'
    environment:
      API_ORIGIN: 'http://localhost:8080'
      ENV: development
