// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
	"paths": {
        "/products": {
            "post": {
                "description": "Creates a product order split in packs given a product amount",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ProductOrder"
                ],
                "summary": "Creates a product order",
                "parameters": [
                    {
                        "description": "Request JSON payload",
                        "name": "_",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateProductOrderPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CreatedPackOrderPayload"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    }
                }
            }
        },
		"/pack_sizes": {
            "post": {
                "description": "Changes the pack sizes to the ones given as params",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PackSizes"
                ],
                "summary": "Changes the pack sizes",
                "parameters": [
                    {
                        "description": "Request JSON payload",
                        "name": "_",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ChangePackSizesPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.APIError"
                        }
                    }
                }
            }
        }
	},
	"definitions": {
		"api.APIError": {
            "properties": {
                "Component": {
                    "type": "ErrorComponent"
                },
                "Context": {
                    "type": "ErrorContext"
                },
                "ContextID": {
                    "type": "string"
                },
                "Message": {
                    "type": "string"
                },
                "Code": {
                    "type": "string"
                },
                "Status": {
                    "type": "int"
                },
                "InnerError": {
                    "type": "error"
                },
                "error": {
                    "description": "Error returned from the API request",
                    "example": "Bad Request",
                    "type": "string"
                }
            },
            "type": "object"
        },
		"api.CreateProductOrderPayload": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                }
            }
        },
        "api.CreatedPackOrderPayload": {
            "type": "object",
            "properties": {
                "amount_of_packs": {
                    "type": "integer"
                },
                "pack_size": {
                    "type": "integer"
                }
            }
        },
		"api.ChangePackSizesPayload": {
            "type": "object",
            "properties": {
                "sizes": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        }
	}
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "pack-delivery-api",
	Description:      "Pack Delivery API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
