basePath: /api
consumes:
- application/json
definitions:
  api.APIError:
    properties:
      Component:
        type: ErrorComponent
      Context:
        type: ErrorContext
      ContextID:
        type: string
      Message:
        type: string
      Code:
        type: string
      Status:
        type: int
      InnerError:
        type: error
      error:
        description: Error returned from the API request
        example: Bad Request
        type: string
    type: object
  api.CreateProductOrderPayload:
    properties:
      amount:
        type: integer
    type: object
  api.CreatedPackOrderPayload:
    properties:
      amount_of_packs:
        type: integer
      pack_size:
        type: integer
    type: object
  api.ChangePackSizesPayload:
    properties:
      sizes:
        items:
          type: integer
        type: array
    type: object
info:
  contact:
    email: dhkelmendi@gmail.com
    name: Dhurim
  description: Pack Delivery API
  title: pack-delivery-api
  version: "0.1"
paths:
  /products:
    post:
      consumes:
      - application/json
      description: Creates a product order split in packs given a product amount
      parameters:
      - description: Request JSON payload
        in: body
        name: _
        required: true
        schema:
          $ref: '#/definitions/api.CreateProductOrderPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.CreatedPackOrderPayload'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.APIError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.APIError'
        "500":
          description: Server Error
          schema:
            $ref: '#/definitions/api.APIError'
      summary: Creates a product order
      tags:
      - ProductOrder
  /pack_sizes:
    post:
      consumes:
      - application/json
      description: Changes the pack sizes to the ones given as params
      parameters:
      - description: Request JSON payload
        in: body
        name: _
        required: true
        schema:
          $ref: '#/definitions/api.ChangePackSizesPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: object
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.APIError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.APIError'
        "500":
          description: Server Error
          schema:
            $ref: '#/definitions/api.APIError'
      summary: Changes the pack sizes
      tags:
      - PackSizes
produces:
- application/json
schemes:
- http
swagger: "2.0"
